#pragma once

#define RGBLIGHT_EFFECT_BREATHING

#define MIDI_ADVANCED

#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY

#define DYNAMIC_MACRO_SIZE 100
#define DYNAMIC_MACRO_DELAY 1

#define COMBO_TERM 72
#define COMBO_KEY_BUFFER_LENGTH 16
#define COMBO_BUFFER_LENGTH 16
#define COMBO_STRICT_TIMER
#define EXTRA_SHORT_COMBOS
